### ISSUE TITLE
Persist application secrets

### ISSUE THREAD

**Issue by hlminh2000** [icgc-argo/charts#1]
Currently, some application secrets are being set manually in kubernetes and persisted with `--reuse-values` in the the helm install command in Jenkinsfile. We want to remove `--reuse-values` in favour of `--reset-values` so all non-secret values are always read from charts rather than being persisted through each deploy, however do not want to have secrets exposed in charts.

Two solutions:
1) [Short-term]: Store secrets as credentials in Jenkins and use `--set` in helm commands to pass to chart.
2) [Long-term]: Set up a [Vault](https://www.vaultproject.io/) instance for secret management and programatically pull in CI

**Comment by blabadi** [comment]
I don't think we should use the 1st short term option, I don't like Jenkins controlling our cluster (subjective) I would prefer using kuberenetes secrets and read them as env vars as short term solution

```
    env:
        - name: "AUTH_TOKEN"
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: webhook_token
```

as for Vault it seems a good as well, it will depend on how many secrets and if things can become manually out of hand then yeah Vault is the way to go.
